# Generated by Django 4.0.1 on 2023-08-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsQuizData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField()),
                ('news_description', models.TextField()),
                ('label', models.BooleanField()),
            ],
        ),
    ]
