# Generated by Django 4.0.1 on 2023-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_livenews', '0002_livenews_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='livenews',
            name='section_id',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livenews',
            name='section_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livenews',
            name='type',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livenews',
            name='web_url',
            field=models.CharField(default=None, max_length=600),
            preserve_default=False,
        ),
    ]
