# Generated by Django 4.0.1 on 2023-09-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_livenews', '0003_livenews_section_id_livenews_section_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livenews',
            name='img_url',
            field=models.CharField(default=0, max_length=600),
            preserve_default=False,
        ),
    ]
